package com.grayzone.app.service.vpn

import java.io.EOFException
import java.io.InputStream
import java.security.MessageDigest

/**
 * Read-only Bloom filter for domain blocking.
 *
 * The shipped filters are generated by scripts/blocklist_tools.ps1. The current
 * raw resources are about 6 MB for ads and 4 MB for adult content, which keeps
 * runtime memory far below a HashSet of the same domains.
 */
class GrayzoneBloomFilter private constructor(
    private val bits: ByteArray,
    private val bitCount: Long,
    private val numHashes: Int
) {
    fun mightContain(domain: String): Boolean {
        if (domain.isEmpty()) return false
        val (h1, h2) = baseHashes(domain)
        for (i in 0 until numHashes) {
            val bitIndex = (h1 + i.toLong() * h2) % bitCount
            val byteIdx = (bitIndex / 8).toInt()
            val bitOff = (bitIndex % 8).toInt()
            if (bits[byteIdx].toInt() and (1 shl bitOff) == 0) return false
        }
        return true
    }

    private fun baseHashes(domain: String): Pair<Long, Long> {
        val digest = SHA256.get()!!.digest(domain.toByteArray(Charsets.UTF_8))
        val h1 = readU32(digest, 0)
        val h2 = readU32(digest, 4).let { if (it == 0L) 1L else it }
        return h1 to h2
    }

    private fun readU32(bytes: ByteArray, offset: Int): Long =
        ((bytes[offset].toLong() and 0xFF) shl 24) or
        ((bytes[offset + 1].toLong() and 0xFF) shl 16) or
        ((bytes[offset + 2].toLong() and 0xFF) shl 8) or
        (bytes[offset + 3].toLong() and 0xFF)

    companion object {
        private const val HEADER_SIZE = 20
        private const val VERSION = 1
        private const val MAX_HASHES = 32
        private const val MAX_FILTER_BYTES = 32 * 1024 * 1024
        private val MAGIC = byteArrayOf(0x47, 0x5A, 0x42, 0x4C)  // "GZBL"

        private val SHA256 = ThreadLocal.withInitial<MessageDigest> {
            MessageDigest.getInstance("SHA-256")
        }

        fun readFrom(stream: InputStream): GrayzoneBloomFilter {
            stream.use { input ->
                val header = ByteArray(HEADER_SIZE)
                readFully(input, header, "Bloom filter header too short")

                require(
                    header[0] == MAGIC[0] && header[1] == MAGIC[1] &&
                        header[2] == MAGIC[2] && header[3] == MAGIC[3]
                ) { "Not a Grayzone bloom filter file (bad magic)" }

                val version = readI32(header, 4)
                require(version == VERSION) { "Unsupported bloom filter version: $version" }

                val numHashes = readI32(header, 8)
                require(numHashes in 1..MAX_HASHES) { "Invalid bloom filter hash count: $numHashes" }

                val bitCount = readI64(header, 12)
                require(bitCount > 0) { "Invalid bloom filter bit count: $bitCount" }
                require(bitCount % 8L == 0L) { "Bloom filter bit count must be byte aligned: $bitCount" }

                val byteCountLong = bitCount / 8L
                require(byteCountLong <= MAX_FILTER_BYTES) {
                    "Bloom filter too large: $byteCountLong bytes"
                }

                val bitArray = ByteArray(byteCountLong.toInt())
                readFully(input, bitArray, "Bloom filter bit array too short")
                require(input.read() == -1) { "Bloom filter contains trailing bytes" }

                return GrayzoneBloomFilter(bitArray, bitCount, numHashes)
            }
        }

        private fun readFully(input: InputStream, target: ByteArray, errorMessage: String) {
            var offset = 0
            while (offset < target.size) {
                val read = input.read(target, offset, target.size - offset)
                if (read == -1) throw IllegalArgumentException(errorMessage, EOFException())
                offset += read
            }
        }

        private fun readI32(d: ByteArray, p: Int): Int =
            ((d[p].toInt() and 0xFF) shl 24) or
                ((d[p + 1].toInt() and 0xFF) shl 16) or
                ((d[p + 2].toInt() and 0xFF) shl 8) or
                (d[p + 3].toInt() and 0xFF)

        private fun readI64(d: ByteArray, p: Int): Long =
            ((d[p].toLong() and 0xFF) shl 56) or
                ((d[p + 1].toLong() and 0xFF) shl 48) or
                ((d[p + 2].toLong() and 0xFF) shl 40) or
                ((d[p + 3].toLong() and 0xFF) shl 32) or
                ((d[p + 4].toLong() and 0xFF) shl 24) or
                ((d[p + 5].toLong() and 0xFF) shl 16) or
                ((d[p + 6].toLong() and 0xFF) shl 8) or
                (d[p + 7].toLong() and 0xFF)
    }
}